name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd videoindexer-mcp
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest pytest-html
        npm ci
        
    - name: Run tests with reports
      run: |
        cd videoindexer-mcp
        mkdir -p junit
        npm run test:reports
        
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: videoindexer-mcp/junit/
